# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'otherwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Otherwindow(object):
    def setupUi(self, Otherwindow):
        Otherwindow.setObjectName("Otherwindow")
        Otherwindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Otherwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 130, 261, 151))
        self.label.setObjectName("label")
        Otherwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Otherwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName("menubar")
        Otherwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Otherwindow)
        self.statusbar.setObjectName("statusbar")
        Otherwindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(Otherwindow)
        self.toolBar.setObjectName("toolBar")
        Otherwindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(Otherwindow)
        QtCore.QMetaObject.connectSlotsByName(Otherwindow)

    def retranslateUi(self, Otherwindow):
        _translate = QtCore.QCoreApplication.translate
        Otherwindow.setWindowTitle(_translate("Otherwindow", "MainWindow"))
        self.label.setText(_translate("Otherwindow", "Hello there!"))
        self.toolBar.setWindowTitle(_translate("Otherwindow", "toolBar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Otherwindow = QtWidgets.QMainWindow()
    ui = Ui_Otherwindow()
    ui.setupUi(Otherwindow)
    Otherwindow.show()
    sys.exit(app.exec_())
